//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.11.18 at 04:15:14 PM CET 
//


package introsde.assignment3.ws.model;

import introsde.jaxb.common.DateAdapter;

import java.util.Date;

import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


@XmlType(name = "PersonType", propOrder = { "id", "firstname", "lastname", "birthdate", "healthProfile" })
public class Person {    
	
    private String firstname;
    private String lastname;
    private Date birthdate;    
    private Long id;
    private HealthProfile healthProfile;
    
    public Person() {
        super();
    }
    
    public Person(Long id, String firstname, String lastname, Date birthdate) {
    	this();
        this.id = id;
        this.firstname = firstname;
        this.lastname = lastname;
        this.birthdate = birthdate;
    }
    
    @XmlElement(name = "personId")
	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

    @XmlElement(required = true)
	public String getFirstname() {
		return firstname;
	}

	public void setFirstname(String firstname) {
		this.firstname = firstname;
	}

	@XmlElement(required = true)
	public String getLastname() {
		return lastname;
	}

	public void setLastname(String lastname) {
		this.lastname = lastname;
	}

	@XmlElement(required = true)
	@XmlJavaTypeAdapter(DateAdapter.class)
	// required format: "yyyy-MM-dd"
	public Date getBirthdate() {
		return birthdate;
	}

	public void setBirthdate(Date birthdate) {
		this.birthdate = birthdate;
	}
	
	@XmlElement
	public HealthProfile getHealthProfile() {
        return healthProfile;
    }

    public void setHealthProfile(HealthProfile healthProfile) {
        this.healthProfile = healthProfile;
    }

	@Override
	public String toString() {
		return "Person [firstname=" + firstname + ", lastname=" + lastname
				+ ", birthdate=" + birthdate + ", id=" + id
				+ ", healthProfile=" + healthProfile + "]";
	}
    
    
}
